"""empty message

Revision ID: 0510704ee015
Revises: 
Create Date: 2023-11-01 13:03:09.858516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0510704ee015'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('agent_location', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], name=op.f('fk_agent_table_event_id_event_table')),
    sa.ForeignKeyConstraint(['listing_id'], ['listing_table.id'], name=op.f('fk_agent_table_listing_id_listing_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_agent_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_table'))
    )
    op.create_table('event_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_table'))
    )
    op.create_table('listing_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_table.id'], name=op.f('fk_listing_table_agent_id_agent_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listing_table'))
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('buyer', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_table')),
    sa.UniqueConstraint('username', name=op.f('uq_users_table_username'))
    )
    op.create_table('financing_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mortgage_calculation', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing_table.id'], name=op.f('fk_financing_table_listing_id_listing_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_financing_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financing_table'))
    )
    op.create_table('user_listing_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing_table.id'], name=op.f('fk_user_listing_table_listing_id_listing_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_user_listing_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_listing_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_listing_table')
    op.drop_table('financing_table')
    op.drop_table('users_table')
    op.drop_table('listing_table')
    op.drop_table('event_table')
    op.drop_table('agent_table')
    # ### end Alembic commands ###
